export const FETCH_USERS_REQUEST_ACTION_TYPE = 'FETCH_USERS_REQUEST_ACTION_TYPE'
export const FETCH_USERS_SUCCESS_ACTION_TYPE = 'FETCH_USERS_SUCCESS_ACTION_TYPE'
export const FETCH_USERS_FAILURE_ACTION_TYPE = 'FETCH_USERS_FAILURE_ACTION_TYPE'

